name: Template Code Checks

on:
  push:
    branches: [main]
    paths:
      - "template/**"
      - "bin/**"
  pull_request:
    branches: [main]
    paths:
      - "template/**"
      - "bin/**"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.10.0"

      - name: Install CLI dependencies
        run: npm install

      - name: Link CLI locally
        run: npm link

      - name: Generate test app
        run: |
          mkdir -p tmp
          cd tmp
          npx create-react-adam test-app-ci --no-e2e
        env:
          CI: true

      - name: Run TypeScript check
        working-directory: ./tmp/test-app-ci
        run: npx tsc --noEmit

      - name: Check formatting
        working-directory: ./tmp/test-app-ci
        run: npm run format:check

      - name: Run linting
        working-directory: ./tmp/test-app-ci
        run: npm run lint:check

      - name: Run build
        working-directory: ./tmp/test-app-ci
        run: npm run build
